require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.1'
install! 'cocoapods', :deterministic_uuids => false

target 'pdftronExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes or fabric on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false,
    :fabric_enabled => false,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'PDFNet', podspec: 'https://nightly-pdftron-uploads.s3.us-west-1.amazonaws.com/stable/2022-10-04/cocoapods/xcframeworks/pdfnet/2022-10-04_stable_rev80283.podspec'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.142.0' })

  post_install do |installer|
    react_native_post_install(installer)
  end

end
